# Object Oriented Programming

**Class**
An abstract definition of a certain type of objects. For example, a human being.

**Object**
An instance of a class. For example, Sandra.

**Attribute**
A feature of the class (class attribute) or of an instance of the class (instance attribute). For example, being a mammal, being male or female, or color of the eyes.

**Method**
An operation that the class or an instance of the class can implement. For example, walking.

**Parameters**
Input taken by a method to influence its behavior. For example, three steps.

**Instantiation**
The process of creating a specific object based on an abstract class.

In [1]:
class HumanBeing(object): #class definition statement
    def __init__(self, first_name, eye_color): #special method called during instantiation
        self.first_name = first_name #first name attribute initialized with parameter value
        self.eye_color = eye_color #eye color value initialized with parameter value
        self.position = 0 #position attribute initialized with 0
    def walk_steps(self, steps): #method definition for walking with steps as parameter
        self.position +=steps #code that changes the position given the steps value

In [2]:
Sandra = HumanBeing("Sandra", "blue") #Instantiation

In [3]:
Sandra.position #Accessing attribute value

0

In [4]:
Sandra.walk_steps(5) #calling the method 
Sandra.position #Accessing the updated position value

5

In [5]:
Sandra.first_name #Accessing attribute value

'Sandra'

In [6]:
Sandra.eye_color #Accessing attribute value

'blue'

## A look at python objects

**int**

Integer Object

In [7]:
n = 5 #new instance n

In [8]:
type(n) #type of the object

int

In [9]:
n.numerator #accessing the attribute

5

In [10]:
n.bit_length() #accessing the method

3

In [11]:
n + n #Applying the + operator

10

In [12]:
2*n #applying the * operator

10

In [13]:
n.__sizeof__() #calling the special method __sizeof__() to get the memory usage in bytes

28

**list**

In [14]:
l = [1,2,3,4] #new instance

In [15]:
type(l) #type of the object

list

In [16]:
l[0] 

1

In [17]:
l.append(10) #method

In [18]:
l+l # + operator

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [19]:
2*l # * operator

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [20]:
sum(l) #applying sum function

20

In [21]:
l.__sizeof__()

104

**ndarray**

In [22]:
import numpy as np

In [23]:
a = np.arange(16).reshape((4,4)) #new instance

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
type(a)

numpy.ndarray

In [26]:
a.nbytes #attribute

64

In [27]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [28]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [29]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [30]:
sum(a)

array([24, 28, 32, 36])

In [31]:
np.sum(a)

120

In [32]:
a.sum()

120

In [33]:
a.__sizeof__()

128

**DataFrame**

In [34]:
import pandas as pd

In [35]:
df = pd.DataFrame(a, columns=list('abcd'))

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [39]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [40]:
df + df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [41]:
2*df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [42]:
np.sum(df)

c:\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


a    24
b    28
c    32
d    36
dtype: int64

In [43]:
df.__sizeof__()

196

**Basics of Python Classes**

In [44]:
class FinancialInstrument(object):
    pass

In [45]:
fi = FinancialInstrument()

In [46]:
type(fi)

__main__.FinancialInstrument

In [47]:
fi

In [48]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x000001C0FE9C0CB0>'

In [49]:
fi.price = 100
fi.price

100

In [50]:
class FinancialInstrument(object): 
    author = 'John Mathew' #definition of a class attribute
    def __init__(self, symbol, price): #special method __init__
        self.symbol = symbol #definition of instance attribute
        self.price = price #definition of instane attribute

In [51]:
FinancialInstrument.author 

'John Mathew'

In [52]:
aapl = FinancialInstrument('AAPL', 100)

In [53]:
aapl.symbol #accessing an instance attribute

'AAPL'

In [54]:
aapl.price #accessing an instance attribute

100

In [55]:
aapl.author #accessing a class attribute

'John Mathew'

In [56]:
aapl.price = 500
aapl.price

500

In [57]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price

In [58]:
fi = FinancialInstrument('AAPL', 100)

In [59]:
fi.get_price()

100

In [60]:
fi.set_price(105)
fi.get_price()

105

In [61]:
fi.price

105

In [62]:
fi.author

'John Mathew'

In [63]:
fi.symbol

'AAPL'

In [64]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol =symbol
        self.__price = price
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [65]:
fi = FinancialInstrument('AAPL', 100)
fi.get_price()


100

In [66]:
# fi.__price #trying to access attribute directly raises an error

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [67]:
fi._FinancialInstrument__price 
# If the class name is prepended with a single leading underscore, direct access and
# manipulation are still possible.

100

In [68]:
fi._FinancialInstrument__price = 150
fi.get_price()

150

In [69]:
fi.set_price(100) #setting back to original price
fi.get_price()

100

In [70]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument #An instance attribute based on an instance of the FinancialInstrument class.
        self.__position_size = position_size #A private instance attribute of the PortfolioPosition class.
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * self.position.get_price()

In [71]:
pp = PortfolioPosition(fi, 10)

pp.get_position_size()

10

In [72]:
pp.get_position_value()

1000

In [73]:
pp.position.get_price()

100

In [74]:
pp.position.set_price(105)

In [75]:
pp.get_position_value()

1050

## Python Data Model

In [79]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z

v_ = Vector(1,2,3)

v_

In [80]:
print(v_)

In [95]:
class Vector(Vector):
    def __repr__(self):
        return  'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [96]:
v= Vector(1,2,3)
v

Vector(1, 2, 3)

In [97]:
print(v)

Vector(1, 2, 3)


In [98]:
class Vector(Vector):
    def __abs__(self):
        return (self.x **2 + self.y **2 + self.z **2)** 0.5
    def __bool__(self):
        return bool(abs(self))

In [99]:
v = Vector(1,2,-1)
abs(v)

2.449489742783178

In [100]:
bool(v)

True

In [101]:
v = Vector()
v

Vector(0, 0, 0)

In [102]:
abs(v)

0.0

In [103]:
bool(v)

False

In [104]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar, self.y * scalar, self.z * scalar)

In [105]:
v = Vector(1,2,3)

v + Vector(2,3,4)

Vector(3, 5, 7)

In [106]:
v*2

Vector(2, 4, 6)

In [118]:
class Vector(Vector):
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')


In [119]:
v = Vector(1,2,3)

In [120]:
len(v)

3

In [121]:
v[0]

1

In [122]:
v[1]

2

In [123]:
v[2]

3

In [124]:
v[4]

IndexError: Index out of range.

In [125]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

v = Vector(1, 2, 3)

In [126]:
for i in range(3): 
    print(v[i])

#This is an example of indirect iteration using index values (via __getitem__)   

1
2
3


In [127]:
for coordinate in v:
    print(coordinate)

#Example of direct iteration over the class instance (using __iter__)

1
2
3


## The Vector Class

In [128]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return 'Vector (%r, %r, %r)' %(self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 + self.y ** 2 + self.z **2)**0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z

    def __mul__(self, scalar):
        return Vector(self.x* scalar, self.y* scalar, self.z* scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0,-3]: return self.x
        elif i in [1,-2]: return self.y
        elif i in [2,-1]: return self.z
        else: raise IndexError('Index out of range.')

    def __iter__(self):
        for i in range(len(self)):
            yield self[i]


            